# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KakaoMap_Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KakaoMap_Clone

pod 'Alamofire'
pod 'JGProgressHUD'
pod 'SDWebImage'
pod 'Toast-Swift'

pod 'KakaoSDKAuth'
pod 'KakaoSDKUser'

pod 'FirebaseAuth'
pod 'FirebaseFirestore'

pod 'GoogleSignIn'

end
